{% set name = "beziers" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/beziers-{{ version }}.tar.gz
  sha256: 8ad31133428a7340b0bda539202eb08ed01677acfb51386f7a33418bbcafd7c0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - pyclipper
    - python >={{ python_min }}

test:
  imports:
    - beziers
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/simoncozens/beziers.py
  summary: Bezier curve manipulation library
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
