schema_version: 1

context:
  name: beziers
  version: "0.6.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/beziers-${{ version }}.tar.gz
  sha256: 8ad31133428a7340b0bda539202eb08ed01677acfb51386f7a33418bbcafd7c0

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - pyclipper
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - beziers
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: Bezier curve manipulation library
  license: MIT
  license_file:
    - LICENSE
  homepage: https://github.com/simoncozens/beziers.py

extra:
  recipe-maintainers:
    - jan-janssen
